'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const sql=fs.readFileSync(__dirname+'/push-notifications-durable-dispatch.sql','utf8');
const expected=[
  [
    "notification_dispatch_jobs",
    "id",
    "uuid",
    true,
    "gen_random_uuid()"
  ],
  [
    "notification_dispatch_jobs",
    "event_id",
    "uuid",
    true,
    null
  ],
  [
    "notification_dispatch_jobs",
    "event_key",
    "text",
    true,
    null
  ],
  [
    "notification_dispatch_jobs",
    "event_type",
    "text",
    true,
    null
  ],
  [
    "notification_dispatch_jobs",
    "title",
    "text",
    true,
    null
  ],
  [
    "notification_dispatch_jobs",
    "body",
    "text",
    true,
    null
  ],
  [
    "notification_dispatch_jobs",
    "source_entity",
    "text",
    true,
    null
  ],
  [
    "notification_dispatch_jobs",
    "source_entity_id",
    "text",
    true,
    null
  ],
  [
    "notification_dispatch_jobs",
    "deep_link",
    "text",
    true,
    null
  ],
  [
    "notification_dispatch_jobs",
    "enqueued_by",
    "uuid",
    true,
    null
  ],
  [
    "notification_dispatch_jobs",
    "stage",
    "text",
    true,
    "'ready'"
  ],
  [
    "notification_dispatch_jobs",
    "next_run_at",
    "timestamp with time zone",
    false,
    "now()"
  ],
  [
    "notification_dispatch_jobs",
    "snapshot_at",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "lease_epoch",
    "bigint",
    true,
    "0"
  ],
  [
    "notification_dispatch_jobs",
    "lease_owner",
    "uuid",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "lease_started_at",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "lease_until",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "acquire_operation_id",
    "uuid",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "acquire_expected_epoch",
    "bigint",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "batch_id",
    "uuid",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "batch_limit",
    "integer",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "batch_prepared_at",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "batch_count",
    "integer",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "settle_operation_id",
    "uuid",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "settled_at",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "settle_reason",
    "text",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "last_error_code",
    "character varying(64)",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "completed_at",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_jobs",
    "created_at",
    "timestamp with time zone",
    true,
    "now()"
  ],
  [
    "notification_dispatch_jobs",
    "updated_at",
    "timestamp with time zone",
    true,
    "now()"
  ],
  [
    "notification_dispatch_attempts",
    "id",
    "uuid",
    true,
    "gen_random_uuid()"
  ],
  [
    "notification_dispatch_attempts",
    "job_id",
    "uuid",
    true,
    null
  ],
  [
    "notification_dispatch_attempts",
    "delivery_id",
    "uuid",
    true,
    null
  ],
  [
    "notification_dispatch_attempts",
    "subscription_ref",
    "uuid",
    true,
    null
  ],
  [
    "notification_dispatch_attempts",
    "batch_id",
    "uuid",
    true,
    null
  ],
  [
    "notification_dispatch_attempts",
    "prepared_epoch",
    "bigint",
    true,
    null
  ],
  [
    "notification_dispatch_attempts",
    "attempt_no",
    "integer",
    true,
    null
  ],
  [
    "notification_dispatch_attempts",
    "claim_token",
    "uuid",
    true,
    null
  ],
  [
    "notification_dispatch_attempts",
    "credentials_hash",
    "bytea",
    true,
    null
  ],
  [
    "notification_dispatch_attempts",
    "stage",
    "text",
    true,
    "'prepared'"
  ],
  [
    "notification_dispatch_attempts",
    "begin_operation_id",
    "uuid",
    true,
    "gen_random_uuid()"
  ],
  [
    "notification_dispatch_attempts",
    "record_operation_id",
    "uuid",
    true,
    "gen_random_uuid()"
  ],
  [
    "notification_dispatch_attempts",
    "ambiguity_operation_id",
    "uuid",
    true,
    "gen_random_uuid()"
  ],
  [
    "notification_dispatch_attempts",
    "release_operation_id",
    "uuid",
    true,
    "gen_random_uuid()"
  ],
  [
    "notification_dispatch_attempts",
    "prepared_at",
    "timestamp with time zone",
    true,
    "now()"
  ],
  [
    "notification_dispatch_attempts",
    "begin_requested_timeout_ms",
    "integer",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "send_owner",
    "uuid",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "send_epoch",
    "bigint",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "send_timeout_ms",
    "integer",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "send_started_at",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "send_deadline_at",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "ambiguity_after",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "ambiguity_at",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "ambiguity_reason",
    "text",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "provider_outcome",
    "text",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "provider_http_status",
    "smallint",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "provider_retry_after_seconds",
    "integer",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "result_recorded_at",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "release_reason",
    "text",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "released_at",
    "timestamp with time zone",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "release_owner",
    "uuid",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "release_epoch",
    "bigint",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "release_attempt_count",
    "integer",
    false,
    null
  ],
  [
    "notification_dispatch_attempts",
    "updated_at",
    "timestamp with time zone",
    true,
    "now()"
  ]
];
assert.equal((sql.match(/^create table public\./gm)||[]).length,2);
for(const [table,column,type,nn] of expected){
 const block=sql.split('create table public.'+table+' (')[1].split('\n);')[0];
 const line=block.split('\n').find(l=>l.trimStart().startsWith(column+' '));
 assert(line,table+'.'+column);
 assert(line.includes(nn?'not null':' null'),column+' nullability');
}
assert(sql.includes('deferrable initially deferred'));
assert(sql.includes('unique(job_id,batch_id,delivery_id)'));
assert(sql.includes("where stage in ('prepared','send_started')"));
assert(sql.includes('octet_length(credentials_hash)=32'));
assert(sql.includes('begin_requested_timeout_ms integer null'));
assert(!sql.includes('release_requested_reason'));
assert.equal((sql.match(/^create (?:unique )?index /gm)||[]).length,6);
for(const table of ['notification_dispatch_jobs','notification_dispatch_attempts']){
 const b=sql.split('create table public.'+table+' (')[1].split('\n);')[0];
 assert(!/^\s+(endpoint|p256dh|auth)\s/gm.test(b),'no raw credentials');
}
assert(!/^alter table public\.(notification_events|notification_deliveries|push_subscriptions|notification_preferences|class_members)\b/im.test(sql));
console.log('Durable schema static contract PASS');
